services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "DoNotUseThisPassword123!"
    ports:
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql

volumes:
  mssql: